ERROR_INVALID_CREDENTIALS = "Invalid credentials"
ERROR_USER_NOT_FOUND = "User not found"
ERROR_LOGOUT_FAILED = "Failed to log out. Please try again later."
ERROR_EMAIL_INVALID = "Invalid email format."
ERROR_NOT_FOUND = "not found."
REMOVE_SUCCESS = "data removed"
RESPONSE_ERROR = "something went wrong"
METHOD_ERROR = "method not allowed"
