ERROR_INVALID_CREDENTIALS = "Invalid credentials"
ERROR_USER_NOT_FOUND = "User not found"
ERROR_OTP_VERIFICATION_FAILED = "OTP verification failed. Please check your OTP."
FAILED_SEND_OTP = "Failed to send OTP: {}"
FAILED_REGISTRATION = "Registration failed"
ERROR_USER_EXIST = "A user with this email already exists."
ERROR_LOGOUT_FAILED = "Failed to log out. Please try again later."
ERROR_EMAIL_INVALID = "Invalid email format."
ERROR_NOT_FOUND = "Not found."
REMOVE_SUCCESS = "data removed"
RESPONSE_ERROR = "something went wrong"
METHOD_ERROR = "method not allowed"
ERROR_OTP_EXPIRED = "OTP Expired"
ERROR_NEW_PASSWORD_NOT_FOUND = "New Password not provided"
NO_FILTER_PROVIDED = (
    "No filters provided. Please provide at least one filter to perform the search."
)
NO_QUERY_PROVIDED = "No search query provided."
ERROR_JOB_ID_REQUIRED = "Job ID is required"
ERROR_NO_APPLICATIONS_FOUND = "No applications found for this job"
ALREADY_APPLIED = "You have already applied for this job."
ALREADY_SAVED = "You have already saved this job."
INVALID_JOB_STATUS = "Invalid job status"
OTP_LIMIT_REACHED_ERROR = "OTP resend limit reached. Try again after 1 hour."
ERROR_STUDENT_ID_REQUIRED = ("Student ID is required",)
ATLEAST_ONE_SKILL_REQUIRED = "Skill set must contain at least one item."
JOB_STATUS_MISSING = "Please provide job id and status"
ACCESS_REQUIRED = "You Don't have access to perform this action"
