ERROR_INVALID_CREDENTIALS = 'Invalid credentials'
ERROR_USER_NOT_FOUND = 'User not found'
ERROR_LOGOUT_FAILED = 'Failed to log out. Please try again later.'
EMAIL_VALIDATE_ERROR='Invalid email format.'
ERROR_OTP_VERIFICATION_FAILED = "OTP verification failed. Please check your OTP."
FAILED_SEND_OTP='Failed to send OTP: {}'
FAILED_REGISTRATION='Registration failed'
ERROR_USER_EXIST="A user with this email already exists."
ERROR_INVALID_CREDENTIALS = "Invalid credentials"
ERROR_USER_NOT_FOUND = "User not found"
ERROR_LOGOUT_FAILED = "Failed to log out. Please try again later."
ERROR_EMAIL_INVALID = "Invalid email format."
ERROR_NOT_FOUND = "not found."
REMOVE_SUCCESS = "data removed"
RESPONSE_ERROR = "something went wrong"
METHOD_ERROR = "method not allowed"
