# Generated by Django 5.1.1 on 2024-12-30 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JobInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "role",
                    models.CharField(
                        choices=[(0, "Developer"), (1, "Designer"), (2, "Manager")],
                        max_length=100,
                    ),
                ),
                ("max_salary", models.PositiveIntegerField()),
                ("min_salary", models.PositiveIntegerField()),
                (
                    "job_type",
                    models.CharField(
                        choices=[(0, "Full Time"), (1, "Part Time"), (2, "Contract")],
                        max_length=50,
                    ),
                ),
                (
                    "job_level",
                    models.CharField(
                        choices=[(0, "Beginner"), (1, "Intermediate"), (2, "Expert")],
                        max_length=100,
                    ),
                ),
                ("vacancies", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "active"), ("expired", "expired")],
                        default="active",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobDescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("education", models.CharField(max_length=100)),
                ("experience", models.PositiveIntegerField()),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("skills", models.TextField()),
                ("description", models.TextField()),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_descriptions",
                        to="jobs.jobinfo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobApply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Received"),
                            (1, "In Review"),
                            (2, "On Hold"),
                            (3, "Shortlisted"),
                            (4, "Interviewing"),
                            (5, "Rejected"),
                            (6, "Salary Negotiation"),
                            (7, "Offered"),
                            (8, "Joined"),
                        ],
                        default=0,
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_owner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_id_applied",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_id_applied",
                        to="jobs.jobinfo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CandidateSaved",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "recruiter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recruiter_id_saved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_id_saved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_id_saved",
                        to="jobs.jobinfo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobSaved",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_job",
                        to="jobs.jobinfo",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_id_saved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Communication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("meta_data", models.JSONField(blank=True, null=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "received_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_received_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sent_from",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_sent_from",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="communication_id",
                        to="jobs.jobapply",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["application"], name="comm_application_index"),
                    models.Index(
                        fields=["created_date"], name="comm_created_date_index"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="jobinfo",
            index=models.Index(fields=["title"], name="job_info_title_index"),
        ),
        migrations.AddIndex(
            model_name="jobinfo",
            index=models.Index(fields=["job_type"], name="job_info_job_type_index"),
        ),
        migrations.AddIndex(
            model_name="jobinfo",
            index=models.Index(fields=["user"], name="job_info_user_index"),
        ),
        migrations.AddIndex(
            model_name="jobinfo",
            index=models.Index(
                fields=["created_date"], name="job_info_created_date_index"
            ),
        ),
        migrations.AddIndex(
            model_name="jobinfo",
            index=models.Index(fields=["id", "user"], name="job_info_id_user_index"),
        ),
        migrations.AddIndex(
            model_name="jobdescription",
            index=models.Index(fields=["job"], name="jd_job_index"),
        ),
        migrations.AddIndex(
            model_name="jobdescription",
            index=models.Index(fields=["user"], name="jd_user_index"),
        ),
        migrations.AddIndex(
            model_name="jobdescription",
            index=models.Index(fields=["created_date"], name="jd_created_date_index"),
        ),
        migrations.AddIndex(
            model_name="jobdescription",
            index=models.Index(fields=["id", "user"], name="jd_id_user_index"),
        ),
        migrations.AddIndex(
            model_name="jobapply",
            index=models.Index(fields=["student"], name="job_apply_student_index"),
        ),
        migrations.AddIndex(
            model_name="jobapply",
            index=models.Index(fields=["job"], name="job_apply_job_index"),
        ),
        migrations.AddIndex(
            model_name="jobapply",
            index=models.Index(fields=["owner"], name="job_apply_owner_index"),
        ),
        migrations.AddIndex(
            model_name="jobapply",
            index=models.Index(
                fields=["created_date"], name="job_apply_created_date_index"
            ),
        ),
        migrations.AddIndex(
            model_name="jobapply",
            index=models.Index(
                fields=["student", "job"], name="job_apply_student_job_index"
            ),
        ),
        migrations.AddIndex(
            model_name="jobapply",
            index=models.Index(
                fields=["job", "student"], name="job_apply_job_student_index"
            ),
        ),
        migrations.AddIndex(
            model_name="candidatesaved",
            index=models.Index(fields=["recruiter"], name="cs_recruiter_index"),
        ),
        migrations.AddIndex(
            model_name="candidatesaved",
            index=models.Index(fields=["job"], name="cs_job_index"),
        ),
        migrations.AddIndex(
            model_name="candidatesaved",
            index=models.Index(fields=["created_date"], name="cs_created_date_index"),
        ),
        migrations.AddIndex(
            model_name="candidatesaved",
            index=models.Index(
                fields=["student", "recruiter"], name="cs_student_recruiter_index"
            ),
        ),
        migrations.AddIndex(
            model_name="jobsaved",
            index=models.Index(fields=["user"], name="job_saved_user_index"),
        ),
        migrations.AddIndex(
            model_name="jobsaved",
            index=models.Index(fields=["job"], name="job_saved_job_index"),
        ),
        migrations.AddIndex(
            model_name="jobsaved",
            index=models.Index(
                fields=["created_date"], name="job_saved_created_date_index"
            ),
        ),
        migrations.AddIndex(
            model_name="jobsaved",
            index=models.Index(fields=["user", "job"], name="job_saved_user_job_index"),
        ),
        migrations.AddIndex(
            model_name="jobsaved",
            index=models.Index(fields=["job", "user"], name="job_saved_job_user_index"),
        ),
    ]
