# Generated by Django 5.1.1 on 2025-08-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="is_paid",
            field=models.BooleanField(default=True),
        ),
    ]
