# Generated by Django 5.1.1 on 2025-09-24 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0002_subject_is_paid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attempt",
            name="score",
            field=models.DecimalField(
                decimal_places=2, default=None, max_digits=6, null=True
            ),
        ),
    ]
