# Generated by Django 5.1.1 on 2025-09-26 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0003_alter_attempt_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="attempt",
            name="maximum_possible_score",
            field=models.DecimalField(
                decimal_places=2, default=None, max_digits=6, null=True
            ),
        ),
    ]
