# Generated by Django 5.1.1 on 2025-09-26 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0004_attempt_maximum_possible_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attempt",
            name="assessment_session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attempts",
                to="assessment.assessmentsession",
            ),
        ),
    ]
