# Generated by Django 5.1.1 on 2025-10-25 11:57

import assessment.models
import functions.common
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0005_alter_attempt_assessment_session"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="question_image",
            field=models.FileField(
                blank=True,
                null=True,
                storage=assessment.models.S3FileStorage(),
                upload_to=functions.common.question_file_rename,
            ),
        ),
    ]
