# Generated by Django 5.1.1 on 2026-06-10 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0006_alter_question_question_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assessmentsession",
            name="payment",
        ),
        migrations.AddField(
            model_name="assessmentsession",
            name="order",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
