# Generated by Codex on 2026-06-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment", "0007_remove_assessmentsession_payment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="is_live",
            field=models.BooleanField(default=False),
        ),
    ]
