# Generated by Django 5.1.1 on 2024-09-30 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_created_date_user_updated_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.PositiveSmallIntegerField(
                blank=True, choices=[(1, "Job Seeker"), (2, "Recruiter")], null=True
            ),
        ),
    ]
