# Generated by Django 5.1.1 on 2025-10-13 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_contactus_subscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[(1, "Job Seeker"), (2, "Recruiter"), (3, "Admin")],
                null=True,
            ),
        ),
    ]
