# Generated by Django 5.1.1 on 2024-10-06 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_otp_expiration"),
        ("accounts", "0003_alter_user_user_type"),
    ]

    operations = []
