from django.urls import path
from .views import *

urlpatterns = [
    path("job_seeker_personal/", job_seeker_personal_details),
    path("job_seeker_general/", job_seeker_general_details),
    path("job_seeker_additional/", job_seeker_additional_details),
    # path("student_profile/", student_profile),
    # path("qualifications/", academic_qualification),
    # path("experience/", work_experience),
    # path("skill_set/", skill_set),
    # path("certifications/", certifications),
    # path("projects/", projects),
    # path("salary/", salary),
    path("social_urls_recruiter/", social_links_recruiter),
    path("social_urls_job_seeker/", social_links_job_seeker),
    path("company_profile/", company_profile),
    path("recruiter_founding/", recruiter_founding_info_details),
    # path("upload_recruiter/", upload_recruiters),
    # path("job_details/", job_details),
    # path("company_id/", company_id),
    path("upload_profile_image/", upload_profile_image),
    path("document/", upload_document),
    # path("upload_document_recruiter/", file_upload_recruiter),
    # path("upload_document_job_seeker/", file_upload_job_seeker),
    path("filter_job_seeker/", job_seeker),
    path("students_all_details/", students_all_details),
    path("application_status/", application_status),
    path("store_fcm_token/", store_fcm_token),
    path(
        "recruiter/<int:recruiter_id>/",
        get_recruiter_details,
        name="get_recruiter_by_id",
    ),
    path("list_recruiters/", get_recruiter, name="list_recruiter"),
    path("list_all_recruiter/", get_all_recruiter, name="list_all_recruiter"),
    path("list_all_applied_applicant/", get_all_applied_applicant, name="list_all_applied_applicant"),
    path("applicant_details/<int:applicant_id>/", get_applicant_details, name="get_applicant_details"),
]
