# Generated by Django 5.1.1 on 2024-12-30 16:58

import django.core.validators
import django.db.models.deletion
import functions.common
import user_profiles.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicQualification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qualification_type", models.CharField(max_length=100)),
                ("institution_name", models.CharField(max_length=200)),
                (
                    "qualification_status",
                    models.CharField(
                        choices=[(0, "Pursuing"), (1, "Completed")], max_length=50
                    ),
                ),
                (
                    "score",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ]
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aq_fk_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["user"], name="aq_user_index"),
                    models.Index(fields=["created_date"], name="aq_created_date_index"),
                    models.Index(fields=["id", "user"], name="aq_id_user_index"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Certifications",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("certification_name", models.CharField(max_length=200)),
                ("institution_name", models.CharField(max_length=200)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ces_fk_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["user"], name="ces_user_index"),
                    models.Index(
                        fields=["created_date"], name="ces_created_date_index"
                    ),
                    models.Index(fields=["id", "user"], name="ces_id_user_index"),
                ],
            },
        ),
        migrations.CreateModel(
            name="FCMToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fcm_token", models.CharField(max_length=255, unique=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["user"], name="fcm_token_user_index"),
                    models.Index(
                        fields=["created_date"], name="fcm_token_created_date_index"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="FoundingInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("organization_type", models.CharField(max_length=200)),
                ("industry_type", models.CharField(max_length=200)),
                ("company_size", models.PositiveSmallIntegerField()),
                ("company_website", models.CharField(max_length=300)),
                ("mission", models.TextField(blank=True, null=True)),
                ("vision", models.TextField(blank=True, null=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="founding_info",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["user"], name="fi_user_index"),
                    models.Index(fields=["created_date"], name="fi_created_date_index"),
                    models.Index(fields=["id", "user"], name="fi_id_user_index"),
                ],
            },
        ),
        migrations.CreateModel(
            name="JobSeekerUploadedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("resume", "Resume"),
                            ("video_resume", "Video Resume"),
                            ("certificate", "Certificate"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        storage=user_profiles.models.S3FileStorage(),
                        upload_to=functions.common.file_rename,
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_seeker_upload_user_id",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["user"], name="jsup_user_index"),
                    models.Index(
                        fields=["created_date"], name="jsup_created_date_index"
                    ),
                    models.Index(fields=["id", "user"], name="jsup_id_user_index"),
                    models.Index(
                        fields=["user", "file_type"], name="jsup_user_fie_type_index"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OrganizationInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_about_us", models.TextField(max_length=500)),
                ("company_website", models.URLField(blank=True)),
                ("address_line_1", models.CharField(max_length=100)),
                (
                    "address_line_2",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                (
                    "postal_code",
                    models.IntegerField(
                        validators=[django.core.validators.MaxValueValidator(999999)]
                    ),
                ),
                ("country", models.CharField(max_length=100)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_info",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["user"], name="oi_user_index"),
                    models.Index(fields=["created_date"], name="oi_created_date_index"),
                    models.Index(fields=["id", "user"], name="oi_id_user_index"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Projects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_name", models.CharField(max_length=200)),
                (
                    "project_organization_name",
                    models.TextField(blank=True, max_length=500, null=True),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ps_fk_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["user"], name="ps_user_index"),
                    models.Index(fields=["created_date"], name="ps_created_date_index"),
                    models.Index(fields=["id", "user"], name="ps_id_user_index"),
                ],
            },
        ),
        migrations.CreateModel(
            name="RecruiterUploadedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            (
                                "organization_registration_number",
                                "Organization Registration Number",
                            ),
                            ("CIN_number", "CIN Number"),
                            ("profile_image", "Profile Image"),
                            ("GST_number", "GST Number"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        storage=user_profiles.models.S3FileStorage(),
                        upload_to=functions.common.file_rename,
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recruiter_upload_user_id",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["user"], name="ruf_user_index"),
                    models.Index(fields=["file_type"], name="ruf_file_type_index"),
                    models.Index(
                        fields=["created_date"], name="ruf_created_date_index"
                    ),
                    models.Index(fields=["id", "user"], name="ruf_id_user_index"),
                    models.Index(
                        fields=["user", "file_type"], name="ruf_user_fie_type_index"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Salary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_salary",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "expected_salary",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "job_search_status",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Actively Looking"),
                            (1, "Passively Looking"),
                            (2, "Not Looking"),
                        ]
                    ),
                ),
                (
                    "notice_period",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Immediately"),
                            (1, "15 days"),
                            (2, "30 days"),
                            (3, "30+ days"),
                        ]
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sy_fk_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["user"], name="sy_user_index"),
                    models.Index(fields=["created_date"], name="sy_created_date_index"),
                    models.Index(fields=["id", "user"], name="sy_id_user_index"),
                ],
            },
        ),
        migrations.CreateModel(
            name="SkillSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skill_name", models.CharField(max_length=100)),
                (
                    "proficiency_level",
                    models.CharField(
                        choices=[
                            (0, "Beginner"),
                            (1, "Intermediate"),
                            (2, "Advanced"),
                            (3, "Expert"),
                        ],
                        max_length=50,
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ss_fk_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["user"], name="ss_user_index"),
                    models.Index(fields=["created_date"], name="ss_created_date_index"),
                    models.Index(fields=["id", "user"], name="ss_id_user_index"),
                ],
            },
        ),
        migrations.CreateModel(
            name="SocialMediaLinkJobSeeker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("platform", models.CharField(max_length=50)),
                ("url", models.URLField(max_length=255)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_media_links_job_seeker",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["user"], name="sm_js_user_index"),
                    models.Index(
                        fields=["created_date"], name="sm_js_created_date_index"
                    ),
                    models.Index(fields=["id", "user"], name="sm_js_id_user_index"),
                ],
            },
        ),
        migrations.CreateModel(
            name="SocialMediaLinkRecruiter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("platform", models.CharField(max_length=50)),
                ("url", models.URLField(max_length=255)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_media_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["user"], name="sm_user_index"),
                    models.Index(fields=["created_date"], name="sm_created_date_index"),
                    models.Index(fields=["id", "user"], name="sm_id_user_index"),
                ],
            },
        ),
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_of_birth", models.DateField()),
                (
                    "gender",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Male"), (1, "Female"), (2, "Other")]
                    ),
                ),
                ("address_line_1", models.CharField(max_length=100)),
                (
                    "address_line_2",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                (
                    "postal_code",
                    models.IntegerField(
                        validators=[django.core.validators.MaxValueValidator(999999)]
                    ),
                ),
                ("country", models.CharField(max_length=100)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sp_fk_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["user"], name="sp_user_index"),
                    models.Index(fields=["created_date"], name="sp_created_date_index"),
                    models.Index(fields=["id", "user"], name="sp_id_user_index"),
                ],
            },
        ),
        migrations.CreateModel(
            name="WorkExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("organization_name", models.CharField(max_length=200)),
                ("designation", models.CharField(max_length=100)),
                ("experience", models.PositiveIntegerField()),
                (
                    "salary",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="we_fk_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["user"], name="we_user_index"),
                    models.Index(fields=["created_date"], name="we_created_date_index"),
                    models.Index(fields=["id", "user"], name="we_id_user_index"),
                ],
            },
        ),
    ]
