# Generated by Django 5.1.1 on 2024-10-05 18:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicQualification",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("institution_name", models.CharField(max_length=200)),
                ("specialization", models.CharField(max_length=100)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Certifications",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("certification_name", models.CharField(max_length=200)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("certificate_url", models.URLField(blank=True, null=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Projects",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("project_name", models.CharField(max_length=200)),
                (
                    "description",
                    models.TextField(blank=True, max_length=500, null=True),
                ),
                ("project_url", models.URLField(blank=True, null=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SkillSet",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("skill_name", models.CharField(max_length=100)),
                ("proficiency_level", models.CharField(max_length=50)),
                ("experience", models.PositiveIntegerField()),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SocialUrls",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("link", models.URLField(blank=True)),
                ("link_title", models.CharField(blank=True, null=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("designation", models.CharField(max_length=100)),
                ("address_line_1", models.CharField(max_length=100)),
                (
                    "address_line_2",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                (
                    "postal_code",
                    models.IntegerField(
                        validators=[django.core.validators.MaxValueValidator(999999)]
                    ),
                ),
                ("country", models.CharField(max_length=100)),
                (
                    "experience",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MaxValueValidator(99)]
                    ),
                ),
                (
                    "gender",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Male"), (1, "Female"), (2, "Other")]
                    ),
                ),
                (
                    "current_salary",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "expecting_salary",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "job_search_status",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Actively Looking"),
                            (1, "Passively Looking"),
                            (2, "Not Looking"),
                        ]
                    ),
                ),
                ("interests", models.TextField(blank=True, max_length=400, null=True)),
                (
                    "notice_period",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Immediately"),
                            (1, "15 days"),
                            (2, "30 days"),
                            (3, "30+ days"),
                        ]
                    ),
                ),
                ("short_bio", models.TextField(max_length=400)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkExperience",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("organization_name", models.CharField(max_length=200)),
                ("designation", models.CharField(max_length=100)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
