# Generated by Django 5.1.1 on 2024-10-06 13:50

import django.db.models.deletion
import functions.common
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profiles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadedFile",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            (0, "Resume"),
                            (1, "Cover Letter"),
                            (2, "Profile Image"),
                            (3, "Company Logo"),
                        ],
                        max_length=50,
                    ),
                ),
                ("file", models.FileField(upload_to=functions.common.file_rename)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
