# Generated by Django 5.1.1 on 2025-01-09 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profiles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobseekeruploadedfile",
            name="file_type",
            field=models.CharField(
                choices=[
                    ("resume", "Resume"),
                    ("video_resume", "Video Resume"),
                    ("profile_image", "Profile Image"),
                    ("certificate", "Certificate"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="salary",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sy_fk_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
