# Generated by Django 5.1.1 on 2025-01-09 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profiles", "0002_alter_jobseekeruploadedfile_file_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organizationinfo",
            name="company_website",
        ),
        migrations.AlterField(
            model_name="foundinginfo",
            name="company_size",
            field=models.CharField(
                choices=[
                    ("1-10", "1-10"),
                    ("11-50", "11-50"),
                    ("51-200", "51-200"),
                    ("201-500", "201-500"),
                    ("501+", "501+"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="foundinginfo",
            name="industry_type",
            field=models.CharField(
                choices=[
                    ("information_technology", "Information Technology"),
                    ("healthcare", "Healthcare"),
                    ("finance", "Finance"),
                    ("education", "Education"),
                    ("manufacturing", "Manufacturing"),
                ],
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="foundinginfo",
            name="organization_type",
            field=models.CharField(
                choices=[
                    ("private", "Private"),
                    ("public", "Public"),
                    ("non_profit", "Non-Profit"),
                    ("government", "Government"),
                    ("start_up", "Start-up"),
                ],
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="foundinginfo",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fi_fk_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="organizationinfo",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="oi_fk_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="socialmedialinkjobseeker",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sml_js_fk_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="socialmedialinkrecruiter",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sml_r_fk_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
