# Generated by Django 5.1.1 on 2025-09-12 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profiles", "0003_remove_organizationinfo_company_website_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="experience",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
