# Generated by Django 5.1.1 on 2024-10-01 16:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profiles", "0003_remove_studentprofile_first_name_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyId",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("registeration_number", models.PositiveSmallIntegerField()),
                ("firm_id", models.PositiveSmallIntegerField()),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CompanyProfile",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("company_email", models.EmailField(max_length=254)),
                ("company_name", models.CharField(max_length=200)),
                ("company_description", models.TextField(max_length=300)),
                ("company_url", models.URLField(blank=True)),
                ("address_line_1", models.CharField(max_length=100)),
                (
                    "address_line_2",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                (
                    "postal_code",
                    models.IntegerField(
                        validators=[django.core.validators.MaxValueValidator(999999)]
                    ),
                ),
                ("country", models.CharField(max_length=100)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobDetails",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("industry", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=200)),
                (
                    "job_type",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Internship"), (1, "Part Time"), (2, "Full Time")]
                    ),
                ),
                ("company_size", models.PositiveSmallIntegerField()),
                ("mission", models.TextField()),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
