# Generated by Django 5.1.1 on 2025-10-01 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_profiles", "0004_studentprofile_experience"),
    ]

    operations = [
        migrations.AddField(
            model_name="academicqualification",
            name="cover_letter",
            field=models.TextField(blank=True, null=True),
        ),
    ]
